name: Rust

on: 
  push:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: sudo apt-get install pkg-config libssl-dev
    - name: Build
      run: cargo build --release
      
    - uses: actions/upload-artifact@master
      with:
        name: linux-build
        path: target/release/babushka
